version: "3.1"
services:

  drupal:
    image: drupal:8.2
    ports:
      - 80:80
      
  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pw
    secrets:
    - postgres_pw

secrets:
  postgres_pw:
    external: true
