apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
      app: jenkins
  ports:
    - name: http
      port: 8080
    - name: jenkins-port
      port: 50000

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
    - name: jenkins-port
      port: 50000

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-np
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
    - name: jenkins-port
      port: 50000
#  externalIPs:
#    - '{{}}'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins
        name: jenkins
        resources: {}
status: {}